### ISSUE TITLE
Manipulate time does not work

### ISSUE THREAD

**Issue by Khazius** [GenerEOS/Qtest#59]
In the current release of Qtest the manipulate time function does not work.

This is because the `restart.sh` and `hard_replay.sh` (this seems unused) still contain the `history_api_plugin` and `history_plugin`

I have worked around this for now by making my tests manually copy a fixed `restart.sh` to the running docker container.

I would make a fork and pull request, but since the npm has a hardcoded docker image felt best if this was solved directly by GenerEOS, so a new docker image could be generated and referenced.

**Comment by quocle108** [comment]
@Khazius thanks. it was fixed at this [commit](https://github.com/GenerEOS/Qtest/commit/639ca79b44341dff716ff350823d689b67baf7bc)
